[windows_servers]
srv-2008.local ansible_host=192.168.1.10
srv-2016.local ansible_host=192.168.1.11
srv-2025.local ansible_host=192.168.1.25

[windows_servers:vars]
ansible_user=Administrateur_Du_Domaine_Ou_Local
ansible_password=VotreMotDePasseSecurise
ansible_connection=winrm
ansible_winrm_server_cert_validation=ignore
ansible_winrm_transport=ntlm
